/* SPDX-FileCopyrightText: 2025-present Kriasoft */
/* SPDX-License-Identifier: MIT */

/**
 * File builder - assembles one server's module: imports, tool types, factory and
 * client type.
 *
 * Output is deterministic (no timestamps) and emits only the imports it uses, so it
 * compiles under `noUnusedLocals`. Imports are type-only, from the SDK alone (ADR-003).
 * One module per server: names never collide across servers, and an app imports only
 * the servers it uses.
 */

import { Node, Project, ts } from "ts-morph";
import type { ServerSnapshot } from "../introspection.js";
import { generateServerClient, hasResources } from "./client-generator.js";
import { hasOutputSchema } from "./tool-input-generator.js";

/** Generate the client module for one introspected server. */
export function generateClientFile(
  serverName: string,
  introspection: ServerSnapshot,
): string {
  const { tools, prompts } = introspection;
  const usesTools = tools.length > 0;
  const usesStructured = tools.some(hasOutputSchema);
  const usesPrompts = prompts.length > 0;
  const usesResources = hasResources(introspection);

  const project = new Project({ useInMemoryFileSystem: true });
  const sourceFile = project.createSourceFile("mcp-client.ts", "", {
    overwrite: true,
  });

  // The types are a snapshot of the server's catalog under one protocol revision
  sourceFile.addStatements([
    `/* Generated by mcp-client-gen from MCP ${introspection.protocolVersion}. Do not edit; regenerate when the server's tools, prompts or resources change. */`,
    "",
  ]);

  sourceFile.addImportDeclaration({
    moduleSpecifier: "@modelcontextprotocol/client",
    namedImports: [
      ...(usesTools ? ["CallToolRequestOptions", "CallToolResult"] : []),
      "Client",
      ...(usesPrompts ? ["GetPromptResult"] : []),
      ...(usesResources ? ["ReadResourceResult"] : []),
      ...(usesPrompts || usesResources ? ["RequestOptions"] : []),
    ],
    isTypeOnly: true,
  });

  if (usesStructured)
    sourceFile.addTypeAlias({
      name: "ToolResult",
      typeParameters: ["T"],
      docs: [
        "Result of a tool with an output schema: `structuredContent` is typed once `isError` is ruled out.",
      ],
      type: "| (CallToolResult & { isError: true }) | (CallToolResult & { isError?: false; structuredContent: T })",
    });

  generateServerClient(sourceFile, serverName, introspection);

  // Separate consecutive type aliases (ts-morph already spaces other declarations)
  for (const alias of sourceFile.getTypeAliases())
    if (Node.isTypeAliasDeclaration(alias.getPreviousSibling()))
      alias.prependWhitespace("\n");

  sourceFile.formatText({
    indentSize: 2,
    semicolons: ts.SemicolonPreference.Insert,
  });

  return sourceFile.getFullText();
}
