/* SPDX-FileCopyrightText: 2025-present Kriasoft */
/* SPDX-License-Identifier: MIT */

/**
 * File builder - assembles the complete TS file: imports, helpers, per-server tool types,
 * client classes and factories.
 *
 * Output is deterministic (no timestamps) and emits only the imports and helpers it uses,
 * so it compiles under `noUnusedLocals`. Each server is a separate class, so bundlers drop
 * the clients you don't use; methods of a used class stay.
 */

import { Project, ts } from "ts-morph";
import type { IntrospectionSuccess } from "../introspection.js";
import { clientClassName, generateClientClass } from "./class-generator.js";
import { hasOutputSchema } from "./tool-input-generator.js";

/** Generated source plus metadata for usage instructions. */
export interface CodegenResult {
  /** Generated TypeScript source code */
  code: string;
  /** Exported factory function names (source of truth for CLI) */
  exports: string[];
}

/**
 * Generate the client file for successfully introspected servers (keyed by server name).
 * @throws When two server names map to the same class name
 */
export function generateClientFile(
  servers: Map<string, IntrospectionSuccess>,
): CodegenResult {
  const classes = new Map<string, string>();
  for (const name of servers.keys()) {
    const className = clientClassName(name);
    const other = classes.get(className);
    if (other !== undefined)
      throw new Error(
        `Servers "${other}" and "${name}" both generate ${className}; give one a different name`,
      );
    classes.set(className, name);
  }

  const results = [...servers.values()];
  const tools = results.flatMap((r) => r.tools);
  const usesTools = tools.length > 0;
  const usesStructured = tools.some(hasOutputSchema);
  const usesPrompts = results.some((r) => r.prompts.length > 0);
  const usesResources = results.some(
    (r) => r.capabilities.resources || r.resources.length > 0,
  );

  const project = new Project({ useInMemoryFileSystem: true });
  const sourceFile = project.createSourceFile("mcp-client.ts", "", {
    overwrite: true,
  });

  sourceFile.addStatements([
    "/* Generated by mcp-client-gen. Do not edit; regenerate instead. */",
    "",
  ]);

  // Type-only: generated code has no runtime dependency on the SDK or this package
  sourceFile.addImportDeclaration({
    moduleSpecifier: "@modelcontextprotocol/client",
    namedImports: [
      ...(usesTools ? ["CallToolResult"] : []),
      "Client",
      ...(usesPrompts ? ["PromptMessage"] : []),
      ...(usesResources ? ["ReadResourceResult"] : []),
      ...(usesTools || usesPrompts || usesResources ? ["RequestOptions"] : []),
    ],
    isTypeOnly: true,
  });
  sourceFile.addImportDeclaration({
    moduleSpecifier: "mcp-client-gen",
    namedImports: ["McpConnection"],
    isTypeOnly: true,
  });

  if (usesTools) addToolHelpers(sourceFile, usesStructured);

  // Names tool types must avoid: imports, helpers, classes and factories
  const typeNames = new Set([
    "CallToolResult",
    "Client",
    "McpConnection",
    "PromptMessage",
    "ReadResourceResult",
    "RequestOptions",
    ...classes.keys(),
  ]);

  const exports: string[] = [];
  for (const [serverName, result] of servers) {
    const className = clientClassName(serverName);
    generateClientClass(sourceFile, serverName, result, typeNames);

    const factoryName = `create${className}`;
    exports.push(factoryName);
    sourceFile.addFunction({
      name: factoryName,
      isExported: true,
      parameters: [{ name: "connection", type: "McpConnection" }],
      returnType: className,
      statements: [`return new ${className}(connection);`],
    });
  }

  sourceFile.formatText({
    indentSize: 2,
    semicolons: ts.SemicolonPreference.Insert,
  });

  return { code: sourceFile.getFullText(), exports };
}

function addToolHelpers(
  sourceFile: ReturnType<Project["createSourceFile"]>,
  structured: boolean,
): void {
  sourceFile.addStatements([
    "",
    "/** Throws when a tool reports failure (`isError`), with its text content as the message. */",
    "function toolResult(result: CallToolResult, toolName: string): CallToolResult {",
    "  if (!result.isError) return result;",
    "  const message = result.content",
    '    .flatMap((block) => (block.type === "text" ? [block.text] : []))',
    '    .join("\\n");',
    "  throw new Error(`Tool '${toolName}' failed: ${message || \"no details\"}`);",
    "}",
    ...(structured
      ? [
          "",
          "/** Typed `structuredContent` of a tool that declares an output schema. */",
          "function structuredResult<T>(result: CallToolResult, toolName: string): T {",
          "  toolResult(result, toolName);",
          "  if (result.structuredContent === undefined)",
          "    throw new Error(`Tool '${toolName}' returned no structured content`);",
          "  return result.structuredContent as T;",
          "}",
        ]
      : []),
    "",
  ]);
}
