/* SPDX-FileCopyrightText: 2025-present Kriasoft */
/* SPDX-License-Identifier: MIT */

/**
 * File builder - assembles the complete TS file: imports, per-server tool types,
 * factories and client types.
 *
 * Output is deterministic (no timestamps) and emits only the imports it uses, so it
 * compiles under `noUnusedLocals`. Imports are type-only, from the SDK alone (ADR-003).
 * Each server is a separate factory, so bundlers drop the clients you don't use.
 */

import { Node, Project, ts } from "ts-morph";
import type { IntrospectionSuccess } from "../introspection.js";
import { clientTypeName, generateServerClient } from "./client-generator.js";
import { hasOutputSchema } from "./tool-input-generator.js";

/** Generated source plus metadata for usage instructions. */
export interface CodegenResult {
  /** Generated TypeScript source code */
  code: string;
  /** Exported factory function names (source of truth for CLI) */
  exports: string[];
}

/**
 * Generate the client file for successfully introspected servers (keyed by server name).
 * @throws When two server names map to the same client type name
 */
export function generateClientFile(
  servers: Map<string, IntrospectionSuccess>,
): CodegenResult {
  const clients = new Map<string, string>();
  for (const name of servers.keys()) {
    const typeName = clientTypeName(name);
    const other = clients.get(typeName);
    if (other !== undefined)
      throw new Error(
        `Servers "${other}" and "${name}" both generate ${typeName}; give one a different name`,
      );
    clients.set(typeName, name);
  }

  const results = [...servers.values()];
  const tools = results.flatMap((r) => r.tools);
  const usesTools = tools.length > 0;
  const usesStructured = tools.some(hasOutputSchema);
  const usesPrompts = results.some((r) => r.prompts.length > 0);
  const usesResources = results.some(
    (r) => r.capabilities.resources || r.resources.length > 0,
  );

  const project = new Project({ useInMemoryFileSystem: true });
  const sourceFile = project.createSourceFile("mcp-client.ts", "", {
    overwrite: true,
  });

  sourceFile.addStatements([
    "/* Generated by mcp-client-gen. Do not edit; regenerate instead. */",
    "",
  ]);

  sourceFile.addImportDeclaration({
    moduleSpecifier: "@modelcontextprotocol/client",
    namedImports: [
      ...(usesTools ? ["CallToolRequestOptions", "CallToolResult"] : []),
      "Client",
      ...(usesPrompts ? ["GetPromptResult"] : []),
      ...(usesResources ? ["ReadResourceResult"] : []),
      ...(usesPrompts || usesResources ? ["RequestOptions"] : []),
    ],
    isTypeOnly: true,
  });

  if (usesStructured)
    sourceFile.addTypeAlias({
      name: "ToolResult",
      typeParameters: ["T"],
      docs: [
        "Result of a tool with an output schema: `structuredContent` is typed once `isError` is ruled out.",
      ],
      type: "| (CallToolResult & { isError: true }) | (CallToolResult & { isError?: false; structuredContent: T })",
    });

  // Tool types end in Input/Output, so they only need to avoid each other
  const typeNames = new Set<string>();
  const exports: string[] = [];
  for (const [serverName, result] of servers) {
    generateServerClient(sourceFile, serverName, result, typeNames);
    exports.push(`create${clientTypeName(serverName)}`);
  }

  // Separate consecutive type aliases (ts-morph already spaces other declarations)
  for (const alias of sourceFile.getTypeAliases())
    if (Node.isTypeAliasDeclaration(alias.getPreviousSibling()))
      alias.prependWhitespace("\n");

  sourceFile.formatText({
    indentSize: 2,
    semicolons: ts.SemicolonPreference.Insert,
  });

  return { code: sourceFile.getFullText(), exports };
}
